# **Keras Basics:**
<br>
Bank currency data: some bank notes are forgeries while the rest are legitimate.

In [1]:
import numpy as np
from numpy import genfromtxt

In [2]:
data=genfromtxt("../DATA/bank_note_data.txt", delimiter=",")

In [3]:
data
#0-forgery
#1-legitimate

In [4]:
labels=data[:,4]

In [5]:
labels

In [6]:
features=data[:,0:4]
features

In [7]:
X=features
y=labels

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test=train_test_split(X, y, random_state=42, test_size=0.33)

In [10]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [11]:
len(X_train)

919

In [12]:
len(X)

1372

In [13]:
len(X_test)
#33% 

453

In [14]:
len(y_train)

919

In [15]:
len(y_test)

453

In [16]:
from sklearn.preprocessing import MinMaxScaler

#this is going to make all the feature data fall in a certain range
#which in turn helps the neural network perform better

In [17]:
X_test.min()

-13.2869

In [18]:
X_train.min()

-13.7731

In [19]:
scaler_object=MinMaxScaler()

In [20]:
scaler_object.fit(X_train)

MinMaxScaler()

In [21]:
scaled_X_train=scaler_object.transform(X_train)

In [22]:
scaled_X_test=scaler_object.transform(X_test)

In [23]:
scaled_X_train.max()

1.0000000000000002

In [24]:
scaled_X_train.min()

0.0

In [25]:
from keras.models import Sequential
from keras.layers import Dense

In [28]:
model=Sequential()

model.add(Dense(4, input_dim=4, activation="relu"))

model.add(Dense(8, activation="relu"))

model.add(Dense(1, activation="sigmoid"))

#too many or too small neurons is going to give bad results
#relu= rectified linear unit (graph)

In [29]:
model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [31]:
model.fit(scaled_X_train, y_train, epochs=50, verbose=2)
#1 epoch means you've gone through all the training data 1 time

Epoch 1/50
 - 0s - loss: 0.1905 - accuracy: 0.9402
Epoch 2/50
 - 0s - loss: 0.1841 - accuracy: 0.9456
Epoch 3/50
 - 0s - loss: 0.1781 - accuracy: 0.9434
Epoch 4/50
 - 0s - loss: 0.1722 - accuracy: 0.9510
Epoch 5/50
 - 0s - loss: 0.1667 - accuracy: 0.9467
Epoch 6/50
 - 0s - loss: 0.1616 - accuracy: 0.9489
Epoch 7/50
 - 0s - loss: 0.1566 - accuracy: 0.9489
Epoch 8/50
 - 0s - loss: 0.1517 - accuracy: 0.9499
Epoch 9/50
 - 0s - loss: 0.1472 - accuracy: 0.9499
Epoch 10/50
 - 0s - loss: 0.1430 - accuracy: 0.9499
Epoch 11/50
 - 0s - loss: 0.1400 - accuracy: 0.9565
Epoch 12/50
 - 0s - loss: 0.1346 - accuracy: 0.9587
Epoch 13/50
 - 0s - loss: 0.1311 - accuracy: 0.9565
Epoch 14/50
 - 0s - loss: 0.1271 - accuracy: 0.9597
Epoch 15/50
 - 0s - loss: 0.1241 - accuracy: 0.9576
Epoch 16/50
 - 0s - loss: 0.1207 - accuracy: 0.9587
Epoch 17/50
 - 0s - loss: 0.1180 - accuracy: 0.9619
Epoch 18/50
 - 0s - loss: 0.1160 - accuracy: 0.9630
Epoch 19/50
 - 0s - loss: 0.1118 - accuracy: 0.9630
Epoch 20/50
 - 0s - l

In [32]:
model.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [33]:
model.metrics_names

['loss', 'accuracy']

In [34]:
from sklearn.metrics import confusion_matrix, classification_report

In [35]:
predictions= model.predict_classes(scaled_X_test)

In [36]:
confusion_matrix(y_test, predictions)

array([[250,   7],
       [  4, 192]], dtype=int64)

In [39]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.98      0.97      0.98       257
         1.0       0.96      0.98      0.97       196

    accuracy                           0.98       453
   macro avg       0.97      0.98      0.98       453
weighted avg       0.98      0.98      0.98       453



In [40]:
model.save("mymodel.h5")

In [41]:
from keras.models import load_model

In [42]:
newmodel=load_model("mymodel.h5")

In [43]:
print(newmodel)

In [44]:
newmodel

In [45]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    